# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2018, Optuna Contributors.
# This file is distributed under the same license as the Optuna package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Optuna 2.4.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-01-14 18:04-0500\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.8.0\n"

#: ../../source/reference/generated/optuna.exceptions.TrialPruned.rst:2
msgid "optuna.exceptions.TrialPruned"
msgstr ""

#: of optuna.exceptions.TrialPruned:1
msgid "Exception for pruned trials."
msgstr "被剪枝 trial 的异常"

#: of optuna.exceptions.TrialPruned:3
msgid ""
"This error tells a trainer that the current :class:`~optuna.trial.Trial` "
"was pruned. It is supposed to be raised after "
":func:`optuna.trial.Trial.should_prune` as shown in the following "
"example."
msgstr ""
"该错误表明当前 :class:`~optuna.trial.Trial` "
"已被剪枝. 它一般会在 "
":func:`optuna.trial.Trial.should_prune` 之后被抛出, 就像下面例子中那样."


#: of optuna.exceptions.TrialPruned:7
msgid ""
":class:`optuna.TrialPruned` is an alias of "
":class:`optuna.exceptions.TrialPruned`."
msgstr ""
":class:`optuna.TrialPruned` 是 "
":class:`optuna.exceptions.TrialPruned` 的一个别名."

#: of optuna.exceptions.TrialPruned:10
msgid "示例"
msgstr ""

